events {
    worker_connections 1024;
}

http {
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Propaga headers de trace W3C para manter o contexto distribuído
    proxy_set_header traceparent  $http_traceparent;
    proxy_set_header tracestate   $http_tracestate;

    upstream product_service {
        server product-service:8001;
    }

    upstream order_service {
        server order-service:8002;
    }

    server {
        listen 8000;

        location /products {
            proxy_pass http://product_service;
        }

        location /checkout {
            proxy_pass http://order_service;
        }

        location /orders {
            proxy_pass http://order_service;
        }

        location /admin {
            proxy_pass http://order_service;
        }

        location /health {
            proxy_pass http://order_service;
        }
    }
}
